/// <summary>
/// @file myLib.h
/// Libraries and namespaces to be included.
/// </summary>
#pragma once
#include <ostream>
#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <random>
#include <fstream>
#include <sstream>
#include <chrono>
#include <filesystem>
#include <list>
#include <deque>

using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
using std::sort;
using std::fixed;
using std::vector;
using std::random_device;
using std::mt19937;
using std::uniform_int_distribution;
using std::ifstream;
using std::ofstream;
using std::getline;
using std::istringstream;
using std::ostringstream;
using std::stoi;
using std::exception;
using std::chrono::high_resolution_clock;
using std::chrono::duration;
using std::partition;
using std::filesystem::directory_iterator;
using std::list;
using std::deque;
using std::ostream;
using std::move;